### ISSUE TITLE
Fail to launch WPTx??-x86_en-us.msi from a path containing a space

### ISSUE THREAD

**Issue by erwanhmsft** [microsoft/eventtracing-processing#2]
When Microsoft.Windows.EventTracing librairies are copied to a directory with a path containing at least one space -- e.g. C:\TMP\New Folder -- WPTx[86|64]-x86_en-us.msi fails to launch upon the first run. An msiexec.exe usage dialog box is displayed.

It appears that the library invokes "msiexec.exe /i C:\TMP\New Folder\WPTx[86|64]-x86_en-us.msi". Because of the embedded space between "New" and "Folder", msiexec fails. The command invoked should instead be: "msiexec.exe" "C:\TMP\New Folder\WPTx[86|64]-x86_en-us.msi".

The workaround consists in copying the librairies to a directory with no space in its full path -- e.g. C:\TMP -- and running the application from there. On the first run, WPTx[86|64]-x86_en-us.msi are installed successfully.

**Comment by maiak** [comment]
This is a known issue, and it is not fixed in version v1.1.0. I will hopefully get a fix into v1.2.0, which is due within the month.

**Comment by maiak** [comment]
This should be fixed in [v1.1.1](https://www.nuget.org/packages/Microsoft.Windows.EventTracing.Processing.All/1.1.1), which I've just released. Let me know if that doesn't fix it.

**Comment by erwanhmsft** [comment]
I confirm that v1.1.1 does fix this issue. Thank you for your support!

**Comment by erwanhmsft** [comment]
Also validated in v1.2
