### ISSUE TITLE
FunctionName does not provide function signature -- unable to differentiate function overloads

### ISSUE THREAD

**Issue by erwanhmsft** [microsoft/eventtracing-processing#3]
The field **ICpuSample.Stack.Frames[n].Symbol.FunctionName** provides only the function name, *not* the function signature. E.g. FunctionName returns "main" instead of "main(int, char * *)". 
This makes it difficult to differentiate between different function overloads. It is possible to use **ICpuSample.Stack.Frames[n].Symbol.AddressRange.BaseAddress.Value** for that purpose, but the result is not quite human-readable.
The best option to differentiate between function overloads would be to return the function signature when available -- i.e. when private symbols are provided. To maintain backward-compatibility, a new field **ICpuSample.Stack.Frames[n].Symbol.FunctionSignature** could be created for that purpose.

**Comment by trgibeau** [comment]
Thanks! We will add it to our backlog!

**Comment by trgibeau** [comment]
Thanks again @erwanh1112 for the request. 

Unfortunately the underlying data source for symbol resolution is language agnostic and there are no plans to support function signatures.  

**IStackSymbol** exposes image and PDB information that can be used in conjunction with PDB parsers such as [MSDIA](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/debug-interface-access-sdk?view=vs-2019) to fetch function signatures.

**Comment by erwanhmsft** [comment]
The challenge with using a PDB parser is that it requires to load every single PDB twice:
1. The Data Layer loads the PDB for its own processing
2. The PDB parser -- e.g. MSDIA -- loads the same PDB to extract function signature

Knowing that PDB loading is on the critical path -- taking ~80% of the processing time in my scenario, the performance hit would be significant. Can **IStackSymbol** help in preventing from loading the same PDB twice? If so, is there some sample code illustrating it?

**Comment by trgibeau** [comment]
TraceProcessor does not load PDBs directly, but instead utilizes library to transcode the PDB into an optimized format called SymCache.  SymCache transcoding happens early in trace processing and by the time IStackSymbol is available the PDB is no longer loaded.
