### ISSUE TITLE
LoadSymbolsForConsoleAsync() sometimes crashes process with code 0xc0000374 (HEAP CORRUPTION)

### ISSUE THREAD

**Issue by erwanhmsft** [microsoft/eventtracing-processing#4]
The following code sequence occasionally (2-10%) crashes with error code 0xc0000374 (HEAP CORRUPTION):

                var symbols = tp.UseSymbols();
                var cpuSampling = tp.UseCpuSamplingData();
                var events = tp.UseGenericEvents();

                tp.Process();

                await symbols.Result.LoadSymbolsForConsoleAsync(
                    new SymCachePath(symCachePath),
                    new SymbolPath(symbolPath), 
                    new string[] { imageName }); // Occasional error 0xc0000374 (HEAP CORRUPTION)

The crash can occur any time within the symbols loading sequence. The crash is random: immediately rerunning the same code usually completes without error.

**Comment by trgibeau** [comment]
There were some changes to symbol loading in recent versions, does it still repro?

**Comment by erwanhmsft** [comment]
@trgibeau, the issue was resolved in EventTracing v1.4 PLUS and insider version of the Windows 10 SDK 21H1. Thanks for the team for addressing swiftly this blocking issue in pre-release mode! The issue will be fully resolved once the Windows 10 SDK 21H1 is RTM, as I understand it
